from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWebEngineWidgets import *
from views import StyleSheethHelper


class Ui_BackgroundForm(object):
    def setupUi(self, BackgroundForm):
        BackgroundForm.setWindowFlags(Qt.FramelessWindowHint)
        BackgroundForm.setObjectName("BackgroundForm")
        BackgroundForm.resize(1074, 782)
        BackgroundForm.setMouseTracking(True)
        BackgroundForm.setAttribute(Qt.WA_TranslucentBackground, True);
        self.backgroundFormLayout = QGridLayout(BackgroundForm)
        self.backgroundFormLayout.setContentsMargins(0, 0, 0, 0)
        self.backgroundFormLayout.setSpacing(3)
        self.backgroundFormLayout.setObjectName("backgroundFormLayout")
        self.Form = QWidget(BackgroundForm)
        self.Form.setMouseTracking(False)
        self.Form.setStyleSheet(StyleSheethHelper.formFormStyleSheet_normal)
        self.Form.setObjectName("Form")
        self.formLayout = QGridLayout(self.Form)
        self.formLayout.setObjectName("formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.headerLayout = QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.btnQtMenu = QPushButton(self.Form)
        self.btnQtMenu.setMinimumSize(QSize(150, 30))
        self.btnQtMenu.setMaximumSize(QSize(150, 30))
        id = QFontDatabase.addApplicationFont("./static/fonts/Montserrat-Regular.ttf")
        font = QFont()
        font.setFamily("Montserrat")
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.btnQtMenu.setFont(font)
        self.btnQtMenu.setStyleSheet(StyleSheethHelper.btnQtMenuStyleSheet_normal)
        self.btnQtMenu.setIcon(QIcon("./static/images/menu.png"))
        self.btnQtMenu.setObjectName("btnQtMenu")
        self.headerLayout.addWidget(self.btnQtMenu)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.closeMinMaxLayout = QHBoxLayout()
        self.closeMinMaxLayout.setContentsMargins(5, 0, 5, -1)
        self.closeMinMaxLayout.setSpacing(10)
        self.closeMinMaxLayout.setObjectName("closeMinMaxLayout")
        self.btnMinimize = QPushButton(self.Form)
        self.btnMinimize.setMaximumSize(QSize(15, 15))
        self.btnMinimize.setStyleSheet(StyleSheethHelper.btnMinimizeStyleSheet_normal)
        self.btnMinimize.setText("")
        self.btnMinimize.setObjectName("btnMinimize")
        self.closeMinMaxLayout.addWidget(self.btnMinimize)
        self.btnMaximize = QPushButton(self.Form)
        self.btnMaximize.setMinimumSize(QSize(15, 15))
        self.btnMaximize.setMaximumSize(QSize(15, 15))
        self.btnMaximize.setStyleSheet(StyleSheethHelper.btnMaximizeStyleSheet_normal)
        self.btnMaximize.setIcon(QIcon("./static/images/maximize.png"))
        self.btnMaximize.setIconSize(QSize(15, 15))
        self.btnMinimize.setIcon(QIcon("./static/images/minus.png"))
        self.btnMinimize.setIconSize(QSize(15, 15))
        self.btnMaximize.setText("")
        self.btnMaximize.setObjectName("btnMaximize")
        self.closeMinMaxLayout.addWidget(self.btnMaximize)
        self.btnClose = QPushButton(self.Form)
        self.btnClose.setMinimumSize(QSize(15, 15))
        self.btnClose.setMaximumSize(QSize(15, 15))
        self.btnClose.setAccessibleDescription("")
        self.btnClose.setStyleSheet(StyleSheethHelper.btnCloseStyleSheet_normal)
        self.btnClose.setText("")
        self.btnClose.setIcon(QIcon("./static/images/close.png"))
        self.btnClose.setIconSize(QSize(15, 15))
        self.btnClose.setObjectName("btnClose")
        self.closeMinMaxLayout.addWidget(self.btnClose)
        self.headerLayout.addLayout(self.closeMinMaxLayout)
        self.formLayout.addLayout(self.headerLayout, 0, 0, 1, 1)

        self.webview = QWebEngineView(self.Form)
        self.webview.setObjectName("webview")
        self.webview.load(self.url)
        self.webview.show()

        self.formLayout.addWidget(self.webview, 1, 0, 1, 1)
        self.backgroundFormLayout.addWidget(self.Form, 0, 0, 1, 1)

        self.retranslateUi(BackgroundForm)
        QMetaObject.connectSlotsByName(BackgroundForm)

    def retranslateUi(self, BackgroundForm):
        _translate = QCoreApplication.translate
        BackgroundForm.setWindowTitle(_translate("BackgroundForm", "QtBrowser"))
        self.btnQtMenu.setText(_translate("BackgroundForm", "QtBrowser"))
